### ISSUE TITLE
Spam Filters not working right

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#10]
Either the spam filter isn't working properly or my logic and understanding is wrong.  Attached files to see if you get the same result.

attachto.log - http://pastebin.com/vypKECHB
attachto.spam-rules - http://pastebin.com/Lw50NGSZ

Nobody "should" be banned but it seems it keeps picking up:

Player Name = [LEG]triforce
    Action = BAN
        1354113648.0: [LEG]triforce 14.201.65.166:2304 19de0f5fa66d2c46c890fa7877ae4f83 - #0 shot 38:37 38:5 Camo1_DZ 7 [0,0,0]

Which to me is only 1 line, and isn't spammed either.  I'm assuming the time's are in seconds so unless it's treating it as minutes I don't know why it's creating this false positive?

**Comment by k4n30** [comment]
Also is it able to convert back to time from the logs rather than 1354113648.0

**Comment by Torndeco** [comment]
Been busy real-life but yes plan on re-converting the time format back to normal battleye format...

Your logic on rules = sound....

Will fix bug asap, found one thing wrong with code.. have it sorted, was working on tracking what else was wrong...
When apparently my server has died or there is a  routing issue 

Thx for the logs makes it alot easier to debug :)

**Comment by Torndeco** [comment]
-removed to avoid confusion-

**Comment by Torndeco** [comment]
Just upload a fix for spam logging.

It now works as one would expect it to...
Was easier than expected :)

Gonna close the issue as believe everything is sorted now

spam filters = fixed
timestamps = fixed
spam logging = fixed / improved
