### ISSUE TITLE
banning by script.whitelist

### ISSUE THREAD

**Issue by bobro4real** [Torndeco/pyBEscanner#11]
Hi all, lpz need help
i have a spectating tool on my server and when i trying to connect with pyBEscanner i banned every time.

my config -
Scan Scripts = strict

my scripts.whitelist
#34 "dayz_logDamage = [name _unit, name _source, _damage];
#34 "dayz_logDamage = [name _unit, name _source, _damage];publicVariableServer "dayz_logDamage";};if (_unit == pl"
#35 "else {publicVariable "dayzUpdateVehicle";};_unit removeAllEventHandlers "HandleDamage";_unit removeAllEventHandlers "Killed"
#67 "openDSInterface;"
#127 " [player,_config] call BIS_fnc_invAdd;
#127 " [player,_config] call BIS_fnc_invAdd;if (_isOk) then {deleteVehicle _holder;} else {_holder setVariable["clai"
#128 "private ['_dummy']; _dummy = [_this,'onload'] call compile preprocessfile '\ca\ui\scripts\server_interface.sqf';"
#223 "rivate ["_dummy"]; _dummy = [_this,"players"] execVM "\ca\ui\scripts\dedicatedServerInterface.sqf";"
#227 "rivate ["_dummy"]; _dummy = [_this,"players"] execVM "\ca\ui\scripts\dedicatedServerInterface.sqf";"

and scripts.log when i trying to enter server. -

29.11.2012 11:47:20: Barmaley (192.168.0.172:2304) d85a6503084ec819c669ee9d027e41af - #2 "until {!(IsNull (findDisplay 46))};
(findDisplay 46) displayAddEventHandler ["keyDown", "_this call fnc_keyDown"];

diag_log fo"
29.11.2012 11:47:20: Barmaley (192.168.0.172:2304) d85a6503084ec819c669ee9d027e41af - #26 "until {!(IsNull (findDisplay 46))};
(findDisplay 46) displayAddEventHandler ["keyDown", "_this call fnc_keyDown"];

diag_log fo"
29.11.2012 11:47:26: Barmaley (192.168.0.172:2304) d85a6503084ec819c669ee9d027e41af - #23 "ong! disconnect and try again!", "BLACK OUT",1];
player enableSimulation false;
};
}; 
dayz_losChance = {
private["_agent","_max"

help me plz
thx

**Comment by Torndeco** [comment]
Answered on forums & update the scripts default whitelist to filter out GCAM hopefully....
Note not fully tested & i may have missed some log entries to filter out
