### ISSUE TITLE
Ban IP

### ISSUE THREAD

**Issue by matsuiman** [Torndeco/pyBEscanner#13]
Would be nice if you could enable a setting to ban the players IP too after scanning.

**Comment by Torndeco** [comment]
Just added option added in servers.ini 

BAN IP

Turns out had most the code in place already... just forgot to finish it.
Didn't get chance to test it fully yet, so will leave this open issue open for the time beening.

There shouldn't be any issues, as was minor code changes

**Comment by matsuiman** [comment]
It's almost working, you just need to remove the port:
82.40.171.107:2325 -1 05.12.2012 16:49:44: Jason for publicvariable hack

**Comment by Torndeco** [comment]
Thanks uploaded a new version.. just done some quick tests & seems ok now...

Note u will need to remove your old pyBEscanner temp directorys...
More info @ Changes.txt
