### ISSUE TITLE
Add IP's to banlist of existing bans

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#19]
Idea is that when a player who has a current ban on them tries to join it checks to see if thier IP is on the banlist and if not add's it :)

Would help to catch up for all the existing bans that dont have IP's attached

note: would require connection log parsing but this was discussed earlier in the project

**Comment by Torndeco** [comment]
Not a bad idea was thinking of adding support for ip banning people with the global bans anyways.
So this shouldn't to hard to add aswell

**Comment by k4n30** [comment]
At the same time, as this would need to read the current banlist (to determine whether to add the new IP or not) could this also be applied to any new bans (most script kiddies appear in more than one log file causing multiple bans currently). Therefore placing this check on all new bans would also prevent doubling up :)

**Comment by Torndeco** [comment]
Gonna close this issue, have opened some seperate issues for upcoming features / ideas..

I believe i have an successful created myself a  nice small spider-web of features depending on each other to work properly
If u notice anything / suggests drop some feedback..
