### ISSUE TITLE
Feature: Server Log & RPT scanning

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/pyBEscanner#22]
- GUID player tracking, more than likely will need to-do https://github.com/Torndeco/pyBEscanner/issues/25
- Option to ban player IP's if they are already GUID / global banned
- Regrex filter support
- - Add ability to add trigger to launch external process i.e
    some user can setup server restarts if server fps drops below a set number for a certain length of time
- Need to avoid parsing the log file, @ server restarts incase its is archived / deleted.
  Maybe offer different options like  to 
  Check for lock file to indicate server restart in progress
  Copy log files to temp folder before parsing (more i/o intensive esp, if admin doesn't rotate logs)
  Define Server Restart times in servers.ini ?

**Comment by k4n30** [comment]
RPT copying to "logs" folder similar to the BE log process as in keeping a running backup?

**Comment by Torndeco** [comment]
Would love to do a similar process i am using for battleye logs...
Where i move the actual log file before i parse & back it up, thus pruning the log files at the same time....

Unfortunately the arma server process keeps the file open all time so i am unable to-do it.

Plus i need to avoid having the file open while parsing it, during a server restart,
incase admin has a script / bat file setup to backup the server logs.

Anyway don't think there is any ideal solution really, so i will prob end up coding the different ways & making it an option
