### ISSUE TITLE
Question about scripts.banlist

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#3]
#128 "ctions\fn_infooplacu.sqf)')};NS_fnc_infooplacu = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_infoo"
#128 "es\functions\fn_dustash.sqf)')};NS_fnc_dustash = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_dusta"
#128 "ctions\fn_dev_record.sqf)')};NS_fnc_dev_record = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_dev_r"
#128 "es\functions\fn_blowseq.sqf)')};

Not sure why this is being used to ban ppl, have had quite a few appeals as this occurs from only logging in. Any reason to justify the bans as I've never seen them before?

**Comment by Torndeco** [comment]
Apparently it is from Namalsk mod,
Downloading Namalsk atm to double check its code-base....

This is idea use for me getting the kicking filters working for in this scenario...
i.e if u aren't running namalsk kick users for running this code

Basicly i don't trust unknown entries with compile entries... 

Anyway i will remove this bans till get the kick-filters working

**Comment by k4n30** [comment]
All good, I don't mind leaving it in and just explain to players that its caused by a mod that shouldn't be loaded. If this can be loaded, what else can?
