### ISSUE TITLE
servers.ini issues

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#31]
Got 2 issues
1. Filters - in "default" section I have - Filters = dayz-default, dayz-weapons-default. If I comment or remove this line pyBEscanner fails to start.  Under the servers section I have reentered the filters so I have dayz-default, dayz-weapons-chernarus (due to multiple servers). When I do this it only loads the filters from the default section and not the server specific, when I only have the lines in the server specific the program fails to run
2. When the missing filters are generated on first program run (ie: *.banlist, *.kicklist, *.whitelist, *.spamlist) not all of the filters lists are created. eg: addbackpackcargo doesn't generate anymore, but addmagazinecargo does.  This makes me wonder if it's not creating these files is it actually checking the filters at all? (if the files don't exist). I know they are blank and don't matter anyway but what to say its not checking the files that are already generated?

**Comment by Torndeco** [comment]
1 = Fixed now, was typo was always loading from default section :(

2 = Went and double checked.... app won't check / create a filter until it encounters the log-file first...
Will look @ changing that tomorrow, so it always makes a blank filter

**Comment by k4n30** [comment]
1 - Awesome
2 - No thats fine, I'd prefer it that way as creating new files (adding them on git) causes conflicts when committing and pulling on another machine - so leave it the way it is, but just mention it in the readme maybe?
