### ISSUE TITLE
[Notice] Be prepared to 1.7.5 

### ISSUE THREAD

**Issue by nanomo** [Torndeco/pyBEscanner#35]
More details here:

http://mydayz.de/en/dayz-news/228-dayz-build-1-7-5-preview

Sorry to bring you more work :P

**Comment by Torndeco** [comment]
Already white-listed the code for the new zombie class that gets spawned...

As for weapons thats relatively quick and easy todo, only takes 2-3 mins to sort out.

Don't think new version has got the nod yet, but its pretty much working state...
Running it atm, via mission fixes...

As for everything else i.e white-listing filters
Might be better off waiting for it to get released + see what we got logged with the new battleye filters...
Atm my logs are @ around 600mb for scripts.log alone, i really need to sort out my battleye filters.

---

But if anyone wants to make up a new set of filters for the weapons & submit them ahead of time...
Go ahead...

**Comment by k4n30** [comment]
Yeah my scripts.log is close to the same :( wish DCBL would sort the filters out already
