### ISSUE TITLE
All Feature Requests 

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/pyBEscanner#41]
pyBEscanner will be just maintance mode from now really..

Will just  fix the bugs that crop up & mantain the filters
Filters will be compatible whenever the next version is done + completed

All feature requests can be directed @ https://github.com/Torndeco/pyBEscanner-v3
It is horrible broken atm + requires python 3.3

**Comment by k4n30** [comment]
Sounds good, can you let us know when pyBEscanner v3 is ready to test so that we can help to find bugs/stablise it :)

**Comment by Torndeco** [comment]
Its in a stable atm if u wanna have a look....

U can have python 2.7 & python 3.3 installed on machine at same time...
Just need to make sure u are  using the right version when launching pyBEscanner....

But i am still only getting ground work done atm, so there will be bugs at some point

i.e 
Besides some extra error handling + nicer console output.
Only new feature atm, is internal bans storage to avoid multiple bans entries

So u might wanna hold off till some new log scanning features are added....
