### ISSUE TITLE
scripts.log

### ISSUE THREAD

**Issue by Yshido** [Torndeco/pyBEscanner#44]
We found the following in our scripts.log. Maybe you can use it to update your filters:

30.12.2012 01:05:06: zazzles: (95.89.57.37:4204) 5a518f81e6315aaf59630775c518cef0 - #14 "teMarkerLocal (""""pmark"""" + (str _i));_pm = createMarkerLocal [(""""pmark"""" + (str _i)), getPos (_entities select _"
30.12.2012 01:05:06: zazzles: (95.89.57.37:4204) 5a518f81e6315aaf59630775c518cef0 - #34 "\medical\publicEH\promptRName.sqf""];"];sleep 0.1;publicVariableServer "remExField";hint " ";sleep 2;Player_Spaw"
30.12.2012 01:05:06: zazzles: (95.89.57.37:4204) 5a518f81e6315aaf59630775c518cef0 - #127 "};delcur ={_x = cursortarget;deleteVehicle _x;dayz_bodyMonitor set [_cursor,'DEL'];Hint "
30.12.2012 01:05:06: zazzles: (95.89.57.37:4204) 5a518f81e6315aaf59630775c518cef0 - #128 "ame = name player;_remote = "if (isServer) then{call compile (""""""dayzLogin2"""" addPublic""+""VariableEventHa"
30.12.2012 01:05:06: zazzles: (95.89.57.37:4204) 5a518f81e6315aaf59630775c518cef0 - #172 "[] spawn {remExField = [nil,nil,";[format [""%2%3%4%5%6%7%8%9%10%11%12%13%14%15%16%17%18%19%20%21%22%23%24%25%26%27%28%29%30"",0"
30.12.2012 15:31:29: Cori: (76.24.231.52:3104) aac65fd61e4ab8a1c8e928021035e943 - #14 "teMarkerLocal (""""pmark"""" + (str _i));_pm = createMarkerLocal [(""""pmark"""" + (str _i)), getPos (_entities select _"
30.12.2012 15:31:29: Cori: (76.24.231.52:3104) aac65fd61e4ab8a1c8e928021035e943 - #34 "ect_setFixServer.sqf';};};_veh=0;veh=", "bowonky"];publicVariableServer "dayzLogin2";usecEpi = player;publicVariableSer"
30.12.2012 15:31:29: Cori: (76.24.231.52:3104) aac65fd61e4ab8a1c8e928021035e943 - #127 "};delcur ={_x = cursortarget;deleteVehicle _x;dayz_bodyMonitor set [_cursor,'DEL'];_x = "
30.12.2012 15:31:29: Cori: (76.24.231.52:3104) aac65fd61e4ab8a1c8e928021035e943 - #128 "(_this select 4)==0))then{_cd=markerText'respawn_west';call compile _cd;remExField=[nil,nil,_cd];publicVariable'remExField';}els"
30.12.2012 15:31:29: Cori: (76.24.231.52:3104) aac65fd61e4ab8a1c8e928021035e943 - #143 "[] spawn {   dayzLogin2 = createTeam ["driver usecEpi;object_SetFixServer={if(isServer&&((_this select 4)==0))then{_cd=markerTex"
30.12.2012 15:31:29: Cori: (76.24.231.52:3104) aac65fd61e4ab8a1c8e928021035e943 - #172 " 4)==0))then{_cd=markerText'respawn_west';call compile _cd;remExField=[nil,nil,_cd];publicVariable'remExField';}else{_this call "
30.12.2012 15:31:29: Cori: (76.24.231.52:3104) aac65fd61e4ab8a1c8e928021035e943 - #177 "ehicle"""", [7], """""""", -5, [[""""expression"""", """"[] spawn reprflcrst;""""]], """"1"""", """"1""""],["""
30.12.2012 23:10:41: SkogisMcSvart: (IP) GUID - #128 "_id = 'M4A1_AIM_SD_camo' spawn compile preprocessFileLineNumbers "r_modz\data\DESM4A1.sqf";;"

Cheers
Yshido

**Comment by Torndeco** [comment]
Thx, add a new scripts rule to ban for createMarkerLocal...
If u come across any others, give a shout...

Btw:- 
I removed the IP/GUID from the last entry, it looks like possible code logged from rmod
Not sure as havent use rmod myself
