### ISSUE TITLE
New Filter Updates

### ISSUE THREAD

**Issue by 1nsaneATT** [Torndeco/pyBEscanner#46]
added line in publicvariable.banlist
#138 "e setDamage 0;dayzUpdateVehicle = [_vehicle,"repair"];if (isServer) then {if (allowConnection) then {dayzUpdateVehicle call "

**Comment by Torndeco** [comment]
Pretty certain that is normal dayz code i.e believe its / was mission fix code for vehicle damage handling

**Comment by 1nsaneATT** [comment]
hm... okay (SetDamage 0)

**Comment by k4n30** [comment]
(SetDamage 0)??? what file and where's an example, set damage 0 is a legit dayz function
