### ISSUE TITLE
Publicvariable.log

### ISSUE THREAD

**Issue by Yshido** [Torndeco/pyBEscanner#48]
Another weird entry

03.01.2013 00:46:07: _iCandy_: (**_.**_.**_.**_:64965) ************************************\* - Value Restriction #25 "remExField" = [,,";[markerType 'bowen'] execVM (markerType 'monky');"]

**Comment by nanomo** [comment]
monky monitor or a branch, ban it :)

**Comment by k4n30** [comment]
definitely a ban
