### ISSUE TITLE
scripts.log

### ISSUE THREAD

**Issue by Yshido** [Torndeco/pyBEscanner#49]
And another one. Please have a look at it if you have some spare time

02.01.2013 18:03:08: moopycoo: (88.207.48.35:2324) bd75bd6f07d7b42ef351a2f01a09c927 - #128 "es\functions\fn_blowseq.sqf)')};NS_fnc_blowseq = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_blows"
02.01.2013 18:03:08: moopycoo: (88.207.48.35:2324) bd75bd6f07d7b42ef351a2f01a09c927 - #128 "ctions\fn_infooplacu.sqf)')};NS_fnc_infooplacu = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_infoo"
02.01.2013 18:03:08: moopycoo: (88.207.48.35:2324) bd75bd6f07d7b42ef351a2f01a09c927 - #128 "es\functions\fn_dustash.sqf)')};NS_fnc_dustash = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_dusta"
02.01.2013 18:03:09: moopycoo: (88.207.48.35:2324) bd75bd6f07d7b42ef351a2f01a09c927 - #128 "ctions\fn_dev_record.sqf)')};NS_fnc_dev_record = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_dev_r"
02.01.2013 18:03:09: moopycoo: (88.207.48.35:2324) bd75bd6f07d7b42ef351a2f01a09c927 - #128 "tions\fn_dzn_snowfall.sqf)')};DZN_fnc_snowfall = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_dzn_s"
02.01.2013 18:03:09: moopycoo: (88.207.48.35:2324) bd75bd6f07d7b42ef351a2f01a09c927 - #128 "ons\fn_dzn_breathfog.sqf)')};DZN_fnc_breathfog = compile preprocessFileLineNumbers 'nst\ns_modules\functions\fn_dzn_b"

**Comment by nanomo** [comment]
every report must include the map and version if it posible!

**Comment by k4n30** [comment]
NS_ indicates namalsk code if this is the server ur running maybe you should create a "dayz-namalsk" folder and a pull request with this code in a whitelist.
