### ISSUE TITLE
Crash on startup with v16

### ISSUE THREAD

**Issue by IvoFalke** [Torndeco/pyBEscanner#52]
C:\Server\pyBEscanner>pyBEscanner.py

---

```
   Loading Config File
```

---

Scanning .Traceback (most recent call last):
  File "C:\Server\pyBEscanner\pyBEscanner.py", line 296, in <module>
    main.start()
  File "C:\Server\pyBEscanner\pyBEscanner.py", line 274, in start
    server["Bans"].checkBans()
AttributeError: 'NoneType' object has no attribute 'checkBans'

**Comment by Torndeco** [comment]
Just uploaded a fix, give it a try now should be working

**Comment by IvoFalke** [comment]
ok, thanks for the fast fix!
works, but i can't get it to do what i want it to do 
but i don't think this is the right place to post my problems.
is there a support forum where i can post my issue, or should i do it here?

**Comment by Torndeco** [comment]
U can post away @ http://opendayz.net/index.php?threads/pybescanner.131/page-5#post-11809 
If u want
