### ISSUE TITLE
Fix [0,0,0] spam rule

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#53]
Whitelist chopper crashes, sorry my mistake

https://github.com/Torndeco/pyBEscanner/commit/8e69a963735090817eb8dfac2c372f8bedfb46b2

**Comment by Torndeco** [comment]
Care to try out the following rule...
Should work

3 59 BAN (?!((#0 "HelicopterExplo)|(#0 "SmallSecondary)).*[0,0,0]$)
