### ISSUE TITLE
Please update scripts.banlist

### ISSUE THREAD

**Issue by Yshido** [Torndeco/pyBEscanner#55]
Just found the following within the scripts-kicks.log:

07.01.2013 13:53:30: humanJudebox: (88.67.250.218:4204) 9f2186fdf127064b457c39c716b91ca1 - #140 "r;removeAllWeapons player; swpn ={_wpns = ["DMR","M9SD","ItemGPS","ItemToolbox","ItemWatch","NVGoggles","ItemMatchbox","ItemMa"
07.01.2013 13:53:30: humanJudebox: (88.67.250.218:4204) 9f2186fdf127064b457c39c716b91ca1 - #140 "r;removeAllWeapons player; swpn ={_wpns = ["DMR","M9SD","ItemGPS","ItemToolbox","ItemWatch","NVGoggles","ItemMatchbox","ItemMa"
07.01.2013 13:53:31: humanJudebox: (88.67.250.218:4204) 9f2186fdf127064b457c39c716b91ca1 - #140 "r;removeAllWeapons player; swpn ={_wpns = ["DMR","M9SD","ItemGPS","ItemToolbox","ItemWatch","NVGoggles","ItemMatchbox","ItemMa"

**Comment by k4n30** [comment]
The reason this is in the scripts-kicks and not scripts-bans is I have had hackers run this on every client causing mass bans (53 to be precise :( ).  For now its best to place it in kicks to avoid false positives on innocent clients getting banned
