### ISSUE TITLE
Spamlist not working

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#58]
So finally moved to v3 (all the commits since it was abandoned and merged into 2)

Got these lines in createvehicle.spamlist -

4 1 BAN .
5 8 BAN ..
3 59 BAN (?!((#0 "HelicopterExplo)|(#0 "SmallSecondary)).*[0,0,0]$)

createvehicle.log -

08.01.2013 23:32:37: Turk (211.30.104.94:2304) d88192f6e173244e71367a3bd6933f94 - #0 "PipeBomb" 68:201 68:187 Survivor2_DZ [10516,2287,6] [0,0,0]
08.01.2013 23:32:42: Turk (211.30.104.94:2304) d88192f6e173244e71367a3bd6933f94 - #0 "PipeBomb" 68:202 68:187 Survivor2_DZ [10513,2290,6] [0,0,0]
08.01.2013 23:32:49: Turk (211.30.104.94:2304) d88192f6e173244e71367a3bd6933f94 - #0 "PipeBomb" 68:203 68:187 Survivor2_DZ [10508,2293,6] [0,0,0]
08.01.2013 23:32:57: Turk (211.30.104.94:2304) d88192f6e173244e71367a3bd6933f94 - #0 "PipeBomb" 68:204 68:187 Survivor2_DZ [10518,2282,6] [0,0,0]

Before this is added to the createvehicle.log (cut and pasted in as wasn't detected when it should've been) pyBEscanner ran fine. However when it encountered this log this crash happened - 

---

```
   Loading Config File
```

---

Scanning ...Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pyBEscanner\pyBEscanner.py", line 296, in <module>
    main.start()
  File "C:\Users\Administrator\Desktop\pyBEscanner\pyBEscanner.py", line 252, in start
    logs_battleye.Scanner(server).scan()
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 216, in scan
    self.scan_battleye_logs(log)
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 95, in scan_battleye_logs
    x)
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 317, in scan_log
    self.spam_detection.add_data(entries_date, entries_guid, entries_ip, entries_port, entries_code, entries_name)
  File "C:\Users\Administrator\Desktop\pyBEscanner\modules\logs_battleye.py", line 465, in add_data
    if re.search(rule, entries_code[x]) or re.search(rule, self.decoder.decode_string(entries_code[x])):
  File "C:\Python27\lib\re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "C:\Python27\lib\re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis

Suggestions? My fault or error in pyBEscanner?

**Comment by Torndeco** [comment]
Looks like u already got it sorted out in the last commit
Yeah shutdown my dayz servers (to many entitled players complaining over nothing) ...
So kinda hard to motivate debug / test this stuff atm

**Comment by k4n30** [comment]
No i still get that error, i just discovered the [ ]'s weren't escaped properly while debugging the issue.

Hopefully this isn't the end of pyBEscanner, I can understand your reason for shutting down the servers though

**Comment by Torndeco** [comment]
Can u check again for the error
My last commit fixed an issue with loading spam rules

**Comment by k4n30** [comment]
Yes that fixed it. 

Cheers :)
