### ISSUE TITLE
Filter Updates

### ISSUE THREAD

**Issue by 1nsaneATT** [Torndeco/pyBEscanner#61]
Add to addmagazinecargo.banlist  and  publicvariable.banlist

Arma2 + DayZ

\"D30\"
\"ARTY_30Rnd_122mmHE_D30\"
\"M119\"
\"ARTY_30Rnd_105mmHE_M119\"

Namalsk

\"nsw_er7mm\"
\"nsw_er7a\"

**Comment by Torndeco** [comment]
Those entries appear to be for nalamsk,
If u got filters setup for nalamsk send a pull request or upload somewhere & i will add to repo

**Comment by 1nsaneATT** [comment]
..........

**Comment by Torndeco** [comment]
Not exactly much to ask for a pull request...
Anyway...

Arma2 + DayZ
The ammo is already banned in the filters

Namalsk

\"nsw_er7mm\"
\"nsw_er7a\"
They are weapons in namalsk in the default loot tables.

Listed in changes for 0.72
http://www.nightstalkers.cz/en_index_dn.php?menu=en_dn_changes
U can disable them via using CfgBuildingLootNamalskNOER7 or CfgBuildingLootNamalskNOSniper.

**Comment by 1nsaneATT** [comment]
Thanks for the detailed answer
