### ISSUE TITLE
Config Option for IP Bans Duration - Done (just needs testing)

### ISSUE THREAD

**Issue by Nashable** [Torndeco/pyBEscanner#62]
Hi there,

I noticed that the scanner adds both a GUID and an IP ban which is great. Only concern with the IP Bans are being added as -1 (permanent) this could create an edge case where players switch IPs and cannot enter the server due to someone else's ban.

Could we have the IP bans added for 72 hours or a week (just needs python to generate a unix timestamp and add the number of seconds to it and log that instead of -1).

GUID bans should remain as is.

**Comment by Torndeco** [comment]
I will add it into pyBEscanner as a config option, once i know how it works.

If u could find out for me find link to info on ban timestamps for bans.txt
i.e
Format & Timezone used local ?

thx

**Comment by matthewlenz** [comment]
ip bans use local epoch time (aka, unix timestamp) or -1 for perm.  99% sure on this one.

**Comment by Torndeco** [comment]
Thanks only recently encounter epoch timestamps, python is more a hobby. 
Will be added in later this week, already coded
Want to get server back up & running to test the changes, to avoid breaking app again

**Comment by k4n30** [comment]
Timelengths on bans in the bans.txt reset every server restart. For this reason times would need to be stored externally.

Eg: Ban someone for 8 hours but your server restarts every 4 hours.  The 8 hour timelimit resets on the server restart effectively making it permanent.

**Comment by matthewlenz** [comment]
You specify a time length in minutes when you ban someone via rcon.  the bans.txt stores them as epoch times (the number of seconds since Dec 31st 1969).  I temp ban people all the time for combat logging and do not have single entry that was converted to perm.  I know this because I specifically state 'combat logging, 2 day' in the entry.  fyi.  the python time module has everything you need.

**Comment by Nashable** [comment]
Just to second Matthew here - with them being epoch timestamps the time the server has been running should be irrelevant.

**Comment by Torndeco** [comment]
Added in latest committed.... should be working...
Needs testing etc, my servers are barely up & running atm i.e need to start bribing players to hop on :P
