### ISSUE TITLE
Upcoming Filter Changes - Done (just needs testing)

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/pyBEscanner#65]
Upcoming Filter Changes change on weekend..

```
#
# Random Comments
#
Rule = Some Random Regrex Rule
   Exception =
   Exception = 
Rule = X
Rule = Y
Rule = Z
  Exception:
# More Random Info
Rule:A
  Action = DELETE  (only valid option)
```

Extra 2 options for spam filters

```
Rule = Some Random Regrex Rule
    Exception = 
    Exception =
    Time = 
    Count = 
    Action = BAN/KICK/LOG
```

App will ignore the leading whitespaces, to allow for indention to make it more human readable...

Basicly it will allow for:
That way u can have add exceptions to filters, would allow for easier spam rules. 
Also would allow for a kick filter that caught alot, but had an exception for a ban rule.

Ability to delete previous loaded filters (i.e default rule) in a custom rule set (currently only supported in spam filters)

---

To highlight the changes, i will rename the filters  directory -> rules.

While at the same time avoid confusion between talking about battleye filters & pyBEscanner filters.

**Comment by k4n30** [comment]
Sounds good :)

**Comment by Torndeco** [comment]
Added in latest committed.... should be working...
I might have missed updating the odd rule.
But fairly easier todo...

Plus pyBEscanner app should exit & tell the rule file & print the line that caused it to fail on parsing.
Note:- This doesn't include regrex errors
