### ISSUE TITLE
Planned Feature -- Update Bans

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/pyBEscanner#67]
Barely started this but anyway...

pyBEutlitiy 
Initial plans are for download via a url
And parse cbl / dwarden bans / banzunion  bans & add missing bans to bans.txt.

**Comment by k4n30** [comment]
:O Finally - Did u get in touch with Doc over at BanZunion? He wanted to create a system to take in pyBEscanner *-bans.txt files to add them to the banzunion list.  Would make all of our jobs easier :)

**Comment by Torndeco** [comment]
Got alot todo atm...

I need to look @ setting server with one of the new upcoming maps, need to get some regular players back on new servers :(

To many servers atm running taviana / namalsk, got barely any players to test pyBEscanner with :(

---

---

He send me a msg at some point wanting to integerate the 2 together...
Already have plans to pull banlists from banzunion + cbl  and have pyBEscanner add the missing bans

So that just leaves uploading the bans...

bans-pyBEscanner.txt  (u can edit the ban reason + based off bans.txt)

For info he has
*-bans.txt
*-spam.txt
*-kicks.txt

They are just standard be logs with return "\n"  char stripped out
I really can't see what else they could need / want imo from pyBEscanner

---

---

Plus i am wary of having pyBEscanner automatic upload bans, without giving admins chances of reviewing them before submitting them.

That & banzunion last i checked has no ban weight system
So only takes 1 bad pyBEscanner bug / or configured wrong and suddenly its submitted a bunch of false bans.

**Comment by k4n30** [comment]
No DEFINATELY not an automated system, but one which provides the admins the ability to copy and paste the contents of a *-bans.txt into banzunion.  Seem's more like it's on his end anyway

new upcoming maps? why bother? why not just do chernarus, still does the same functions :p

**Comment by Torndeco** [comment]
Downloading bans = done
