### ISSUE TITLE
Spam Rule

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#69]
Using this in new spam rules:

Rule = .*\ [0,0,0\ ]               <--------   (Spaces not between \ & [ in actual rule, but github hides \ if no space :( )
    Exception = #0 "HelicopterExplo
        Exception = #0 "SmallSecondary
    Count = 3
    Time = 59
    Action = BAN

Gives:
Error rule file C:\DayZ\pyBEscanner\rules\dayz-default\createvehicle.spamlist
Exception = #0 "HelicopterExplo

Ideas? Did I do it wrong, or is it a bug?

**Comment by Torndeco** [comment]
Try the latest commit now, should work now...

I had it checking for Exceptions :(
Anyway i changed to look for Exception in the code, makes more sense.

**Comment by k4n30** [comment]
Yeah it loads now, but now I'm getting false positives like before, eg:

Player Name = Real Bavilion
    Action = BAN
        30.01.2013 19:44:55: Real Bavilion 122.61.58.18:2404 c52481ff438bf87c6a0c2b06012851bd - #0 "WeaponHolder_ItemTent" 73:173 [5718,9958,33]
        30.01.2013 06:07:16: Real Bavilion 122.61.58.18:2404 c52481ff438bf87c6a0c2b06012851bd - #0 "WeaponHolder_ItemTent" 14:208 [3866,7309,37]
        30.01.2013 06:35:44: Real Bavilion 122.61.58.18:2404 c52481ff438bf87c6a0c2b06012851bd - #0 "WeaponHolder_ItemTent" 14:460 [7704,4394,44]
        30.01.2013 10:11:05: Real Bavilion 122.61.58.18:2404 c52481ff438bf87c6a0c2b06012851bd - #0 "ParachuteWest" 3:167 [9072,6355,282]
        30.01.2013 13:23:54: Real Bavilion 122.61.58.18:2404 c52481ff438bf87c6a0c2b06012851bd - #0 "ParachuteWest" 3:141 [12412,20437,305]

As you can see there is no [0,0,0] in there so either it doesn't like the rule or it doesn't like the exception :(  This is for the exact line posted in the OP

**Comment by k4n30** [comment]
Think I got it working. Needed the 0,0,0 to be [0],[0],[0] :(

I'll test it for a few more days before creating a pull request :)

**Comment by Torndeco** [comment]
Something is gone wrong there i think :(

Had a look @ the code and nothing standing out
Any chance u can send me the createvehicle logs files that caused the above Ban
& your createvehicle.spamlist, so i can try & reproduce it

Message on opendayz forums etc..

**Comment by k4n30** [comment]
I fixed it - see my last comment

**Comment by Torndeco** [comment]
The problem is "[0,0,0]" and "[[0],[0].[0]]" are the exact same thing regrex wise.

I have double checked this out via some simple python code.
Also looked over code & noticed 1 bug and i have already fixed it.

But i really need to get my hands on your spam filters & the createvehicle.log that it happens on...
So i can find out step through the code & see exactly is going on..

Rather fix the issue, as it appears to be a symptom of a bigger bug in spam code...

**Comment by k4n30** [comment]
File sent :)
