### ISSUE TITLE
Add addweaponcargo.log support

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#7]
http://code.google.com/p/dayz-community-banlist/source/browse/filters/addweaponcargo.txt

Doesn't seem to log much at all, but have noticed that it does log count restrictions which is usually the indication of a hacker/ scripter spawning in items.  The recommended interval is MaxAddWeaponCargoPerInterval 16 1 which IMO is impossible to find 16 weapons in 1 second, therefore I suggest we add support for parsing it and banning for "Count Restriction"

**Comment by Torndeco** [comment]
Don't see why not, plus u already have it added in the filters u put in for a pull request :)

**Comment by k4n30** [comment]
yeah the filters are there but the underlying code isnt :(

**Comment by Torndeco** [comment]
Ah new battleye log file will add it in now...
Thx for pointing it out
