### ISSUE TITLE
Spam filters?

### ISSUE THREAD

**Issue by k4n30** [Torndeco/pyBEscanner#9]
Do these work on all the filters or just setpos at this stage?

**Comment by Torndeco** [comment]
They work on all files

**Comment by Torndeco** [comment]
Also if u want to test out a rule....
If u type an action that isnt KICK / BAN it will only get logged in the spam log file...
Nice to test out new rule if u want...

i.e 
10 10 TEST-RULE .

It would get logged in spams log file with 
 Action = TEST-RULE...
